language: python

os:
  - linux

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - docker build -t deploy_surge .
  - docker images

script:
  - (docker run -e SURGE_LOGIN=${SURGE_LOGIN} -e SURGE_TOKEN=${SURGE_TOKEN} -e PR_NUMBER=${TRAVIS_PULL_REQUEST} deploy_surge); echo $?
