project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /content/en/*.md
    translation: /content/%two_letters_code%_%original_file_name%
